// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJoZyEoOnxJ3z2DKyNE9RETM4I_uCOMW0',
    appId: '1:271038415168:web:30c3698943c8a7eb763aa5',
    messagingSenderId: '271038415168',
    projectId: 'mema2-ac698',
    authDomain: 'mema2-ac698.firebaseapp.com',
    databaseURL: 'https://mema2-ac698-default-rtdb.firebaseio.com',
    storageBucket: 'mema2-ac698.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdtdAjbzu6dk1ax-RyOlu4x1RIm_qm01E',
    appId: '1:271038415168:android:5660e98f8c53f3e6763aa5',
    messagingSenderId: '271038415168',
    projectId: 'mema2-ac698',
    databaseURL: 'https://mema2-ac698-default-rtdb.firebaseio.com',
    storageBucket: 'mema2-ac698.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj_gBlv5yezdF7LczZOGRJ1N-B93CABE8',
    appId: '1:271038415168:ios:70087ebd0c3438bd763aa5',
    messagingSenderId: '271038415168',
    projectId: 'mema2-ac698',
    databaseURL: 'https://mema2-ac698-default-rtdb.firebaseio.com',
    storageBucket: 'mema2-ac698.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj_gBlv5yezdF7LczZOGRJ1N-B93CABE8',
    appId: '1:271038415168:ios:70087ebd0c3438bd763aa5',
    messagingSenderId: '271038415168',
    projectId: 'mema2-ac698',
    databaseURL: 'https://mema2-ac698-default-rtdb.firebaseio.com',
    storageBucket: 'mema2-ac698.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJoZyEoOnxJ3z2DKyNE9RETM4I_uCOMW0',
    appId: '1:271038415168:web:35ef7ec14acfc2e0763aa5',
    messagingSenderId: '271038415168',
    projectId: 'mema2-ac698',
    authDomain: 'mema2-ac698.firebaseapp.com',
    databaseURL: 'https://mema2-ac698-default-rtdb.firebaseio.com',
    storageBucket: 'mema2-ac698.appspot.com',
  );
}
