// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEvBOYhtdu-vzb1bqXU0MXCcA32L_H2gM',
    appId: '1:1073539569536:web:b5c87f5d0a33d40f399365',
    messagingSenderId: '1073539569536',
    projectId: 'displayd-6bce3',
    authDomain: 'displayd-6bce3.firebaseapp.com',
    storageBucket: 'displayd-6bce3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMkQsQFjoGzp93Q0195R7eb1FYPjCxmVo',
    appId: '1:1073539569536:android:049c2ed978b2f911399365',
    messagingSenderId: '1073539569536',
    projectId: 'displayd-6bce3',
    storageBucket: 'displayd-6bce3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsDbrA2F5AO7gj-ocuqbzelgJcMxVI0Xc',
    appId: '1:1073539569536:ios:718a28b329f4d63f399365',
    messagingSenderId: '1073539569536',
    projectId: 'displayd-6bce3',
    storageBucket: 'displayd-6bce3.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsDbrA2F5AO7gj-ocuqbzelgJcMxVI0Xc',
    appId: '1:1073539569536:ios:718a28b329f4d63f399365',
    messagingSenderId: '1073539569536',
    projectId: 'displayd-6bce3',
    storageBucket: 'displayd-6bce3.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEvBOYhtdu-vzb1bqXU0MXCcA32L_H2gM',
    appId: '1:1073539569536:web:a4046661ea6fcede399365',
    messagingSenderId: '1073539569536',
    projectId: 'displayd-6bce3',
    authDomain: 'displayd-6bce3.firebaseapp.com',
    storageBucket: 'displayd-6bce3.appspot.com',
  );

}